### ISSUE TITLE
Gui small bugs

### ISSUE THREAD

**Issue by Maievmau** [ActiveAgeingHKR/JavaFXunit#10]
@SE-Design (Kashif) and i found this bug just now, not a priority but should be reported to you guyz.

To replicate it: after the log in just click on the button (not the tab) Visitors or Visitor Schedule and then the button Back => the tabs aren't visible anymore.
Clicking on any other button and then Back again, will bring back the tabs again. However, the app hangs for a couple of seconds. It also hangs when it goes to the Visitor and Visitor Schedule via respective buttons as well.
*Clicking on the tabs doesn't recreate this bug.

![guibug](https://cloud.githubusercontent.com/assets/17614378/21643716/30b9ceca-d28a-11e6-80b3-21ef066f14d8.PNG)

`You clicked Visitors!
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 78 more
`

**Comment by Maievmau** [comment]
I took the liberty of assigning Rolandas so he'd see it. Anyone else is welcome to fix it if needed.

**Comment by ghost** [comment]
The app "hangs" is because the tabPane isn't done well. There are like 10 tabs, which means all of those initialize method will happen at once. 
Clicking back in visitor or visitorSchedule should work properly.
