### ISSUE TITLE
Unassigned Employees Uncompleted

### ISSUE THREAD

**Issue by chellerific** [ActiveAgeingHKR/JavaFXunit#6]
There is no available button for the admin to be able to view available employees that can be assigned to customers.

**Comment by chellerific** [comment]
Kind reminder regarding this issue: I still cannot find this feature implemented anywhere. I'm not sure if there should be a button for this like unassigned customers.

**Comment by IuliuNicolae** [comment]
If one select a specific day from calendar and one specific employee from
list and click on "NEW" utton the program will show for how many hours this
ermployee is available

**Comment by chellerific** [comment]
Sorry, I just tried that but I don't see any changes being made anywhere. Could you screenshot me how it's supposed to work?

**Comment by IuliuNicolae** [comment]
I am sorry for problems. When you select a specific date from calendar,
does the program display this date?

**Comment by chellerific** [comment]
Yes it does, and I don't see any changes anywhere in the program. I also tried clicking the date, then "New", and nothing happens.

**Comment by IuliuNicolae** [comment]
When I open the schedule page I could see the message"You must choose a
date first!!!!".

I open the calendar and I pick another day(not today 2017-01-05) after that
I choose the today date and the program display "You choose :2017-01-05";
I select one employee from table
I select one customer from table
I click "New " button and theprogram displays "Hours: X" (in my exemple
8...that means 8 hours remains to work)
I now it is not the best solution...and I try to find one better, but for
me it works.

**Comment by chellerific** [comment]
Ah I see it now... OK, I think it would be better to write some brief hints on the GUI on what the user should do and what the hours that will appear actually mean, not just "Hours:". I'm also still not sure how 8 hours can indicate that the employee is available. I click different possibilities on different dates and the hours are always 8.

**Comment by IuliuNicolae** [comment]
:) I am glad that it works...I will do some changes. Did you check the
unsigned customer button. I hope that I fix the bug...

**Comment by chellerific** [comment]
Yeah, it's working I can close that issue :) , all that page needs is a clearer procedure shown to user and I can close this one too

**Comment by IuliuNicolae** [comment]
Hello,
I made some changes in schedule of employees. After one will select the
date, it is possible to view the schedule only for this specific date and
it is also possible to wiew only the available employees (with less of 8
hours- work). I hope that the code works not only on my computer :).

**Comment by Maievmau** [comment]
What's the difference between the Employee Schedule and the Visitor Schedule? How are we using this?

Edit: I could make a new schedule, that works. However, it just looks like a visitor schedule (i'm probably wrong tho.)

**Comment by chellerific** [comment]
Ah @IuliuNicolae , I pulled and I couldn't make those updates you did happen. However, there's a restriction I can see where I cannot validate a schedule when an employee has done 8h of work for the day, and I am wondering if that is enough to fulfill / solve this issue.

**Comment by IuliuNicolae** [comment]
Hello,
After one select a date, it will apperar two new buttons "View available
employees/View all employees" and "View all schedule/View schedule by
date". I thinck that could be usefull to manage the schedule process. I
wonder if those work only on my computer.

**Comment by IuliuNicolae** [comment]
Hello,
There is a new version of employee's schedule. The date problem is fixed
(it is not necessary to select another date before the current one).

**Comment by Maievmau** [comment]
I crashed it by entering letters in the schedule time. :'3
So it won't fetch anything from the database anymore until i edit it directly from it.

`Sending 'GET' request to URL : https://localhost:8181/MainServerREST/api/employeeschedule/
Response Code : 500
Jan 06, 2017 8:27:08 PM aajavafx.Schedule1Controller initialize
SEVERE: null
java.io.IOException: Server returned HTTP response code: 500 for URL: https://localhost:8181/MainServerREST/api/employeeschedule/
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.panos.SSLConnection.doGet(SSLConnection.java:144)
	at aajavafx.Schedule1Controller.getSchedule(Schedule1Controller.java:221)
	at aajavafx.Schedule1Controller.initialize(Schedule1Controller.java:152)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.access$2700(FXMLLoader.java:103)
	at javafx.fxml.FXMLLoader$IncludeElement.constructValue(FXMLLoader.java:1143)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:746)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
	at aajavafx.LoginController.handleButtonLoginAction(LoginController.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1769)
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1657)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8413)
	at javafx.scene.control.Button.fire(Button.java:185)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
sun.security.ssl.SSLSocketFactoryImpl@4fe654fb
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)`

**Comment by IuliuNicolae** [comment]
It is a problem from database....delete all schedueles and create
anothers...

**Comment by Maievmau** [comment]
I fixed it myself, like i said. I can just edit it and it's back on. But there should be a measure against it maybe (just a pop up maybe)? Since it will break every time like that though it's easy to fix. (Not my call just reporting bugs. :D)

Also if i put in a schedule for the same employee and the same date from 12.30 to 13.00 and 14.30 to 16.00 => it shows as 7.3 hours left. XD If i put 12:30, i crash it again.
Similarly, it showed 4.3 hours left instead of the expected value of 4.5h.

Also, i don't see the buttons "View available employees/View all employees" and "View all schedule/View schedule by date" appear. :(

**Comment by IuliuNicolae** [comment]
I fixed the time calculation and the buttons

**Comment by gwq2427527** [comment]
Hello 
Due to I got a new laptop. I have a problem when I open the project on my new laptop.
I got  a error when I click login. Is my computer problem???


Sending 'GET' request to URL : https://localhost:8181/MainServerREST/api/managers/username/JackBlack
Response Code : 404
java.io.FileNotFoundException: https://localhost:8181/MainServerREST/api/managers/username/JackBlack
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1885)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1884)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1457)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.panos.SSLConnection.doGet(SSLConnection.java:144)
	at aajavafx.LoginController.getPassword(LoginController.java:137)
	at aajavafx.LoginController.handleButtonLoginAction(LoginController.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1769)
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1657)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
LOAD PAGE EXCEPTION: java.io.FileNotFoundException: https://localhost:8181/MainServerREST/api/managers/username/JackBlack
You clicked me!
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8411)
	at javafx.scene.control.Button.fire(Button.java:185)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:352)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:275)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:388)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:387)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: https://localhost:8181/MainServerREST/api/managers/username/JackBlack
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1836)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.panos.SSLConnection.doGet(SSLConnection.java:139)
	... 60 more

**Comment by IuliuNicolae** [comment]
404 errror code is strange to receive...It looks as the page could not be
found...does the server work properly?

**Comment by gwq2427527** [comment]
it is ok now

**Comment by IuliuNicolae** [comment]
If you use the url " https://localhost:8181/MainServerREST/api/managers/
username/JackBlack" in a browser, isit OK?

**Comment by lukashkatman** [comment]
I reckon, you need to replace "password1" for JackBlack with an encrypted
password on your database. Since you are starting on your new laptop, make
sure to update the database table of manager.
BR,
Lokesh

**Comment by swashyson** [comment]
404 is not found, must be the URL that does not exist.
You have https://localhost:8181/MainServerREST/api/managers/
Isn't it like this, https://localhost:8181/MainServerREST-master/api/managers/ sometimes depending on your pull?

**Comment by chellerific** [comment]
Sup @IuliuNicolae , I saw the changes you've made, View Schedule By Date works nice, but now when I toggle the Select all/available employees and click Select Available Employees I get a FXML error.

**Comment by IuliuNicolae** [comment]
*It is strange that *Unassigned customers does not work...I test it many
times;
Select all/available employees could be a problem from the time of
schedule...Does it works if you create a new schedule,
I work with the calculation of time I got a bug.

**Comment by chellerific** [comment]
@IuliuNicolae Unassigned customers works now, that was a mistake on my part. Adding a new schedule works as well, the only bug is when you click "Select available employees".

**Comment by IuliuNicolae** [comment]
What error did you get?

**Comment by chellerific** [comment]
FXML loader errors. 

I think that it would be immensely helpful if a step by step instruction is printed on the GUI for the normal user. This page has now become quite confusing on which order the user should press buttons etc.

e.g. just write at the side of the page a numbered instruction like 

1) Choose date
2) Select employee

and so on

**Comment by IuliuNicolae** [comment]
It is a very good sugestion and I am working on it, but from my last upload
one must not choose a date (in the beginning the date is allways the
current date) I am curious it it works on your computer. It is possible to
get error if click on "NEW" button without select one employee and one
customer.Now  I try to fix this.

**Comment by IuliuNicolae** [comment]
I fixed the FXML load error (I hoe)

**Comment by chellerific** [comment]
Sorry, I pulled and don't see it fixed.

**Comment by IuliuNicolae** [comment]
May I see the FXML error? I will clone a new project to find what is wrong

**Comment by IuliuNicolae** [comment]
The button "Select available employees" is working. I open the schedule
scene and I select one employee and one customer and I create a schedule
from 08.00 to 20.00 and I validate this one and I get a new schedule. If I
click on button "Select available employee" I get a list without this
employee who has more than 8 hours. If I click on "Select all employees"
the list has also this employee.
